spring:
  datasource:
    url: jdbc:mysql://localhost:3306/emsdb1?createDatabaseIfNotExist=true
    username: root
    password: {cypher}2e44c3a8e713b765016e9726406e368208cfe1b0a4d85dbe4d4a6de79f7a6f30
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none  
1qaz2wsx@
